version: '2'

service:
  drone-server:
    image: drone/drone:0.5
    env_file: .env
    ports:
      - 443:8000
    volumes:
      - ./drone:/var/lib/drone
    restart: always

  drone-agent:
    image: drone/drone:0.5
    command: agent
    restart: always
    depends_on: [ drone-server ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DRONE_SERVER=ws://drone-server:8000/ws/broker
      DRONE_OPEN=true
